# Generated by Django 5.0 on 2023-12-22 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('total_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1024)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_without_tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tax_name', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('line_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.order')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'ordering': ['item_name', 'quantity'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='purchase.ordernumber'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.supplier'),
        ),
    ]
