# Generated by Django 5.0 on 2023-12-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='tax_name',
            field=models.CharField(max_length=1024),
        ),
    ]
