# Generated by Django 5.0 on 2023-12-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_lineitem_tax_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(editable=False),
        ),
    ]
