# Generated by Django 5.0 on 2023-12-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='line_total',
        ),
    ]
